name: Java CI with Maven

on:
  push:
    branches: [ main ]  # Runs tests when you push to main branch
  pull_request:
    branches: [ main ]  # Runs tests on pull requests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build and Run Tests
        run: mvn clean verify
